# Training and Test datasets

In [1]:
import tensorflow as tf

x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]
#Training Data

# Evaluation our model using this test dataset
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]
#Test Data

#Training 데이터와 Test 데이터를 분리해야 한다.

X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])
#Placeholder를 이용하기 때문에 학습 데이터와 테스트 데이터를 feed_dict 따로 넣어주기만 하면 된다.

W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))
#tf.placeholder()는 입력 데이터를 만들 때 주로 사용한다. (실제 훈련 예제를 제공하는 변수) - 초기값을 지정할 필요 없다. (모델 입력시 변경되지 않을 데이터)
#tf.Variable()은 데이터의 상태를 저장할 때 주로 사용한다. (가중치나 편향 등의 학습 가능한 변수) - 초기값을 지정해야 한다. (학습 되는 데이터)
#http://stackoverflow.com/questions/36693740/whats-the-difference-between-tf-placeholder-and-tf-variable

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1)) #Cross entropy
# Try to change learning_rate to small numbers
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-10).minimize(cost) #최적화

# Correct prediction Test model
prediction = tf.arg_max(hypothesis, 1) #arg_max : 가장 큰 값의 인덱스
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer()) #초기화

    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)
        #Training 데이터만으로 학습을 한다.

    # predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))
    #Test 데이터만으로 예측과 정확도 측정

0 6.44227 [[ 0.85962057  1.28496659  1.46813238]
 [ 1.9539367   0.96308261  0.64203686]
 [ 1.76346159 -0.38934138  1.80743122]]
1 6.44227 [[ 0.85962057  1.28496659  1.46813238]
 [ 1.9539367   0.96308261  0.64203686]
 [ 1.76346159 -0.38934138  1.80743122]]
2 6.44227 [[ 0.85962057  1.28496659  1.46813238]
 [ 1.9539367   0.96308261  0.64203686]
 [ 1.76346159 -0.38934138  1.80743122]]
3 6.44227 [[ 0.85962057  1.28496659  1.46813238]
 [ 1.9539367   0.96308261  0.64203686]
 [ 1.76346159 -0.38934138  1.80743122]]
4 6.44227 [[ 0.85962057  1.28496659  1.46813238]
 [ 1.9539367   0.96308261  0.64203686]
 [ 1.76346159 -0.38934138  1.80743122]]
5 6.44227 [[ 0.85962057  1.28496659  1.46813238]
 [ 1.9539367   0.96308261  0.64203686]
 [ 1.76346159 -0.38934138  1.80743122]]
6 6.44227 [[ 0.85962057  1.28496659  1.46813238]
 [ 1.9539367   0.96308261  0.64203686]
 [ 1.76346159 -0.38934138  1.80743122]]
7 6.44227 [[ 0.85962057  1.28496659  1.46813238]
 [ 1.9539367   0.96308261  0.64203686]
 [ 1.76346159 -0

141 6.44227 [[ 0.85962057  1.28496659  1.46813238]
 [ 1.9539367   0.96308261  0.64203686]
 [ 1.76346159 -0.38934138  1.80743122]]
142 6.44227 [[ 0.85962057  1.28496659  1.46813238]
 [ 1.9539367   0.96308261  0.64203686]
 [ 1.76346159 -0.38934138  1.80743122]]
143 6.44227 [[ 0.85962057  1.28496659  1.46813238]
 [ 1.9539367   0.96308261  0.64203686]
 [ 1.76346159 -0.38934138  1.80743122]]
144 6.44227 [[ 0.85962057  1.28496659  1.46813238]
 [ 1.9539367   0.96308261  0.64203686]
 [ 1.76346159 -0.38934138  1.80743122]]
145 6.44227 [[ 0.85962057  1.28496659  1.46813238]
 [ 1.9539367   0.96308261  0.64203686]
 [ 1.76346159 -0.38934138  1.80743122]]
146 6.44227 [[ 0.85962057  1.28496659  1.46813238]
 [ 1.9539367   0.96308261  0.64203686]
 [ 1.76346159 -0.38934138  1.80743122]]
147 6.44227 [[ 0.85962057  1.28496659  1.46813238]
 [ 1.9539367   0.96308261  0.64203686]
 [ 1.76346159 -0.38934138  1.80743122]]
148 6.44227 [[ 0.85962057  1.28496659  1.46813238]
 [ 1.9539367   0.96308261  0.64203686]


# Learning rate
<img src="Images/lab7_1.png">

# Nomalize

<img src="Images/lab7_2.png">

<img src="Images/lab7_3.png">

In [2]:
import numpy as np
import random

def MinMaxScaler(data):
    numerator = data - np.min(data, 0) #데이터 - 최소값. np.min(data, 0) : data의 최소값, 0차원에 대해. 열에 대한 최소값이 구해진다.
    denominator = np.max(data, 0) - np.min(data, 0) #최대값 - 최소값
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7) #0으로 나눠지는 것을 막기 위해 작은 값을 더한다.

xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])
#데이터가 크거나 들쑥날쑥한 경우에는 정규화를 해줘야 한다.

# very important. It does not work without it.
xy = MinMaxScaler(xy)
print(xy)
#정규화하지 않고 진행할 경우 값이 발산해서 Nan이 나온다.

x_data = xy[:, 0:-1] #전체 행을 가져온다, 각 행의 0 ~ index-1 행까지 가져온다.
y_data = xy[:, [-1]] #전체 행을 가져온다, 각 행의 마지막 행만 가져온다.

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4]) #전체 요소의 개수는 n, 각 요소는 4개씩
Y = tf.placeholder(tf.float32, shape=[None, 1]) #전체 요소의 개수는 n, 각 요소는 1개씩

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')
#tf.placeholder()는 입력 데이터를 만들 때 주로 사용한다. (실제 훈련 예제를 제공하는 변수) - 초기값을 지정할 필요 없다. (모델 입력시 변경되지 않을 데이터)
#tf.Variable()은 데이터의 상태를 저장할 때 주로 사용한다. (가중치나 편향 등의 학습 가능한 변수) - 초기값을 지정해야 한다. (학습 되는 데이터)
#http://stackoverflow.com/questions/36693740/whats-the-difference-between-tf-placeholder-and-tf-variable

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y)) #평균 제곱 오차

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost) #최적화

# Launch the graph in a session.
with tf.Session() as sess:
    # Initializes global variables in the graph.
    sess.run(tf.global_variables_initializer()) #초기화
    
    for step in range(101):
        cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)


[[ 0.99999999  0.99999999  0.          1.          1.        ]
 [ 0.70548491  0.70439552  1.          0.71881782  0.83755791]
 [ 0.54412549  0.50274824  0.57608696  0.606468    0.6606331 ]
 [ 0.33890353  0.31368023  0.10869565  0.45989134  0.43800918]
 [ 0.51436     0.42582389  0.30434783  0.58504805  0.42624401]
 [ 0.49556179  0.42582389  0.31521739  0.48131134  0.49276137]
 [ 0.11436064  0.          0.20652174  0.22007776  0.18597238]
 [ 0.          0.07747099  0.5326087   0.          0.        ]]
0 Cost:  1.00072 
Prediction:
 [[-0.95883536]
 [ 0.1618742 ]
 [-0.19608256]
 [-0.50727671]
 [-0.49069303]
 [-0.44204131]
 [-0.38210535]
 [ 0.21758243]]
1 Cost:  1.00066 
Prediction:
 [[-0.95878714]
 [ 0.16191787]
 [-0.19604582]
 [-0.50724769]
 [-0.49065876]
 [-0.44200838]
 [-0.3820841 ]
 [ 0.21760225]]
2 Cost:  1.0006 
Prediction:
 [[-0.9587388 ]
 [ 0.16196147]
 [-0.19600907]
 [-0.50721884]
 [-0.49062458]
 [-0.44197544]
 [-0.38206288]
 [ 0.21762207]]
3 Cost:  1.00053 
Prediction:
 [[-0.9586

58 Cost:  0.997071 
Prediction:
 [[-0.95604348]
 [ 0.16440132]
 [-0.19395438]
 [-0.50560111]
 [-0.48871297]
 [-0.44013757]
 [-0.38087523]
 [ 0.21872976]]
59 Cost:  0.997009 
Prediction:
 [[-0.95599532]
 [ 0.16444483]
 [-0.19391784]
 [-0.50557232]
 [-0.48867884]
 [-0.44010472]
 [-0.38085404]
 [ 0.21874955]]
60 Cost:  0.996946 
Prediction:
 [[-0.95594728]
 [ 0.1644884 ]
 [-0.19388112]
 [-0.50554341]
 [-0.48864481]
 [-0.440072  ]
 [-0.38083282]
 [ 0.21876934]]
61 Cost:  0.996883 
Prediction:
 [[-0.95589912]
 [ 0.16453186]
 [-0.19384447]
 [-0.5055145 ]
 [-0.48861063]
 [-0.44003922]
 [-0.38081166]
 [ 0.21878907]]
62 Cost:  0.99682 
Prediction:
 [[-0.95585108]
 [ 0.16457543]
 [-0.19380781]
 [-0.50548565]
 [-0.4885765 ]
 [-0.44000638]
 [-0.38079044]
 [ 0.21880886]]
63 Cost:  0.996757 
Prediction:
 [[-0.95580304]
 [ 0.16461888]
 [-0.19377121]
 [-0.50545681]
 [-0.48854241]
 [-0.43997356]
 [-0.38076925]
 [ 0.21882865]]
64 Cost:  0.996694 
Prediction:
 [[-0.95575494]
 [ 0.16466242]
 [-0.19373453]

# MNIST data

In [3]:
from tensorflow.examples.tutorials.mnist import input_data
# Check out https://www.tensorflow.org/get_started/mnist/beginners for
# more information about the mnist dataset
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)

nb_classes = 10

# MNIST data image of shape 28 * 28 = 784
X = tf.placeholder(tf.float32, [None, 784]) #인풋. 28 x 28 형 이미지라 784
# 0 - 9 digits recognition = 10 classes
Y = tf.placeholder(tf.float32, [None, nb_classes]) #정답 레이블. 10개. one-hot encoding

W = tf.Variable(tf.random_normal([784, nb_classes])) #가중치의 shape는 들어오는 값 input(784), 나가는 값 output(nb_classes)
b = tf.Variable(tf.random_normal([nb_classes]))#편향은 출력값과 같다.
#레이어의 개수에 따라 shape가 달라진다.

# Hypothesis (using softmax)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b) #활성 함수

cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1)) #Cross Entropy
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost) #최적화

# Test model
is_correct = tf.equal(tf.arg_max(hypothesis, 1), tf.arg_max(Y, 1)) #축을 기준으로 예측값과 정답레이블의 정답 인덱스(값이 가장 큰 요소) 비교
# Calculate accuracy
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32)) #정확도 계산

# parameters
training_epochs = 15 #전체 데이터 세트를 한 번 다 학습 시키는 것이 1 epoch
batch_size = 100 #한 번에 100개씩 학습(epoch이 더 큰 개념. 한 에폭 안에 100개씩 잘라서 학습)

with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer()) #초기화
    # Training cycle
    for epoch in range(training_epochs): #15번 에폭 반복
        avg_cost = 0
        total_batch = int(mnist.train.num_examples / batch_size) #배치 사이즈에 따라 몇 번의 반복을 해야 될지 계산

        for i in range(total_batch):
            batch_xs, batch_ys = mnist.train.next_batch(batch_size) #next_batch를 통해 다음 100개씩 잘라서 가져온다.
            c, _ = sess.run([cost, optimizer], feed_dict={X: batch_xs, Y: batch_ys}) #가져온 데이터를 넣고 session.run()
            avg_cost += c / total_batch #?? total_batch가 맞나? batch_size아님?

        print('Epoch:', '%04d' % (epoch + 1), 'cost =', '{:.9f}'.format(avg_cost))

    print("Learning finished")

    # Test the model using test sets
    print("Accuracy: ", accuracy.eval(session=sess, feed_dict={X: mnist.test.images, Y: mnist.test.labels}))
    #session.run() 대신에 accuracy.eval을 사용해도 된다.
    #인풋 : 이미지, 정답레이블
    #학습할 때 사용한 데이터 대신 테스트 데이터를 사용해야 한다.

    # Get one and predict
    r = random.randint(0, mnist.test.num_examples - 1) #랜덤하게 하나의 값을 불러 온다.
    print("Label: ", sess.run(tf.argmax(mnist.test.labels[r:r + 1], 1)))
    print("Prediction: ", sess.run(tf.argmax(hypothesis, 1), feed_dict={X: mnist.test.images[r:r + 1]}))

    # don't know why this makes Travis Build error.
    # plt.imshow(
    #     mnist.test.images[r:r + 1].reshape(28, 28),
    #     cmap='Greys',
    #     interpolation='nearest')
    # plt.show()




Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
Epoch: 0001 cost = 2.609114408
Epoch: 0002 cost = 1.065122392
Epoch: 0003 cost = 0.856706764
Epoch: 0004 cost = 0.753912530
Epoch: 0005 cost = 0.689749216
Epoch: 0006 cost = 0.643747267
Epoch: 0007 cost = 0.608576023
Epoch: 0008 cost = 0.581048547
Epoch: 0009 cost = 0.558474733
Epoch: 0010 cost = 0.539308574
Epoch: 0011 cost = 0.522599912
Epoch: 0012 cost = 0.508082677
Epoch: 0013 cost = 0.495561296
Epoch: 0014 cost = 0.483565744
Epoch: 0015 cost = 0.473545129
Learning finished
Accuracy:  0.8905
Label:  [2]
Prediction:  [2]
