# Simple 1D array and slicing 

In [1]:
import tensorflow as tf
import numpy as np
import pprint

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession() 
#Session은 생성 전 구성이 완료 되어야
#InteractiveSession은 생성 후 구성이 가능

t = np.array([0., 1., 2., 3., 4., 5., 6.]) #1차원 배열. 숫자 뒤 점은 float을 정확히 표현하기 위해.
pp.pprint(t)
print(t.ndim) # rank 차원
print(t.shape) # shape
print(t[0], t[1], t[-1]) #-1은 마지막 요소
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.])
1
(7,)
0.0 1.0 6.0
[ 2.  3.  4.] [ 4.  5.]
[ 0.  1.] [ 3.  4.  5.  6.]


# 2D Array

In [2]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape

array([[  1.,   2.,   3.],
       [  4.,   5.,   6.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])
2
(4, 3)


# Shape, Rank, Axis

In [3]:
t = tf.constant([1,2,3,4])
tf.shape(t).eval() #tf에서 shape와 자료형 출력
#rank는 1(차원). 대괄호의 수 / 2

array([4], dtype=int32)

In [4]:
t = tf.constant([[1,2],
                 [3,4]])
tf.shape(t).eval()
#rank는 2(차원). 대괄호의 수 / 2

array([2, 2], dtype=int32)

In [5]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).eval()
#rank는 4(차원). 대괄호의 수 / 2
#각각 작은 단위부터 역으로 계산해 가면 된다. 가장 작은 대괄호에 4개씩, 2번째 대괄호에 3개씩, 그 다음 대괄호에 2개씩, 마지막 대괄호에 전체 1개
# [
#     [
#         [
#             [1,2,3,4], 
#             [5,6,7,8],
#             [9,10,11,12]
#         ],
#         [
#             [13,14,15,16],
#             [17,18,19,20], 
#             [21,22,23,24]
#         ]
#     ]
# ]

array([1, 2, 3, 4], dtype=int32)

<img src="Images/lab8_1.png">

# Matmul VS multiply

In [6]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
print("Metrix 1 shape", matrix1.shape)
print("Metrix 2 shape", matrix2.shape)

tf.matmul(matrix1, matrix2).eval()

Metrix 1 shape (1, 2)
Metrix 2 shape (2, 1)


array([[ 12.]], dtype=float32)

In [7]:
(matrix1*matrix2).eval() #내적 곱과 그냥 곱은 다르다.

array([[ 6.,  6.],
       [ 6.,  6.]], dtype=float32)

# Broadcasting

In [8]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
(matrix1+matrix2).eval() #같은 shape이므로 1:1로 대응해서 계산된다.

array([[ 5.,  5.],
       [ 5.,  5.]], dtype=float32)

In [9]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
(matrix1+matrix2).eval() #shape이 다르더라도 연산할 수 있게 해 주는 것이 Broadcast
#https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

array([[ 5.,  5.],
       [ 5.,  5.]], dtype=float32)

# Reduce Mean/Sum

In [10]:
tf.reduce_mean([1, 2], axis=0).eval() #Int형으로 평균이 구해진다

1

In [11]:
x = [[1., 2.],
     [3., 4.]]


tf.reduce_mean(x).eval() #축 없이 쓰면 모든 값을 평균한다.

2.5

In [12]:
tf.reduce_mean(x, axis=0).eval() #축에 따라 결과가 달라진다.

array([ 2.,  3.], dtype=float32)

In [13]:
tf.reduce_mean(x, axis=1).eval() #축에 따라 결과가 달라진다. 큰 값일수록 안쪽

array([ 1.5,  3.5], dtype=float32)

In [14]:
tf.reduce_mean(x, axis=-1).eval() #마지막 축

array([ 1.5,  3.5], dtype=float32)

In [15]:
tf.reduce_sum(x).eval() #sum 함수. 축 없이 쓰면 모든 값을 더한다.

10.0

In [16]:
tf.reduce_sum(x, axis=0).eval() #축에 따라 결과가 달라진다. 

array([ 4.,  6.], dtype=float32)

In [17]:
tf.reduce_sum(x, axis=-1).eval() #축에 따라 결과가 달라진다. 큰 값일수록 안쪽

array([ 3.,  7.], dtype=float32)

In [18]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval() #안 쪽에 있는 값들을 더하고 그 값들의 평균

5.0

# Argmax

In [19]:
x = [[0, 1, 2],
     [2, 1, 0]]
tf.argmax(x, axis=0).eval() #축에 따라 결과가 달라진다.

array([1, 0, 0])

In [20]:
tf.argmax(x, axis=1).eval() #축에 따라 결과가 달라진다. 큰 값일수록 안쪽

array([2, 0])

In [21]:
tf.argmax(x, axis=-1).eval() #축에 따라 결과가 달라진다. 큰 값일수록 안쪽. 마지막 인덱스는 -1로 쓸 수도 있다.

array([2, 0])

# Reshape, squeeze, expand_dims

In [22]:
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape

(2, 2, 3)

In [23]:
tf.reshape(t, shape=[-1, 3]).eval() #(?, 3)의 형태로 reshape
#마지막 값(3)은 보통 그대로 가져간다. 이 값만 유지되면 대체로 값이 섞이지 않는다.

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
tf.reshape(t, shape=[-1, 1, 3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [25]:
tf.squeeze([[0], [1], [2]]).eval() #Squeeze로 펴준다.

array([0, 1, 2], dtype=int32)

In [26]:
tf.expand_dims([0, 1, 2], 1).eval() #expand_dims 차원을 추가한다.

array([[0],
       [1],
       [2]], dtype=int32)

# One hot

In [27]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval() #depth3 = 0~2
#one_hot을 하게 될 경우 자동으로 expand를 하게 된다.

array([[[ 1.,  0.,  0.]],

       [[ 0.,  1.,  0.]],

       [[ 0.,  0.,  1.]],

       [[ 1.,  0.,  0.]]], dtype=float32)

In [28]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3) 
tf.reshape(t, shape=[-1, 3]).eval() #(?, 3)의 형태로 reshape
#expand 된 결과를 reshape 해 줘야 원하는 결과를 얻는다.

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.]], dtype=float32)

# Casting

In [29]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval() #int32로 캐스팅

array([1, 2, 3, 4], dtype=int32)

In [30]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval() #int32로 캐스팅

array([1, 0, 1, 0], dtype=int32)

# Stack

In [31]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

# Pack along first dim.
tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [32]:
tf.stack([x, y, z], axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

# Ones like and Zeros like

In [33]:
x = [[0, 1, 2],
     [2, 1, 0]]

tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [34]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

# Zip

In [35]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [36]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9


# Transpose

In [37]:
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
pp.pprint(t.shape)
pp.pprint(t)

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [38]:
t1 = tf.transpose(t, [1, 0, 2])
pp.pprint(sess.run(t1).shape)
pp.pprint(sess.run(t1))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 3,  4,  5],
        [ 9, 10, 11]]])


In [39]:
t = tf.transpose(t1, [1, 0, 2])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [40]:
t2 = tf.transpose(t, [1, 2, 0])
pp.pprint(sess.run(t2).shape)
pp.pprint(sess.run(t2))

(2, 3, 2)
array([[[ 0,  6],
        [ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10],
        [ 5, 11]]])


In [41]:
t = tf.transpose(t2, [2, 0, 1])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


# randomtf.random_normal([3]).eval()

In [42]:
tf.random_normal([3]).eval()

array([ 1.10390568,  0.39864376,  0.28955397], dtype=float32)

In [43]:
tf.random_uniform([2]).eval() #2개 랜덤

array([ 0.97096503,  0.81880283], dtype=float32)

In [44]:
tf.random_uniform([2, 3]).eval() #2개의 요소. 3개씩 랜덤 -> 2 x 3

array([[ 0.73535359,  0.172755  ,  0.8229636 ],
       [ 0.63548863,  0.45738375,  0.99275303]], dtype=float32)