# Training and Test datasets

In [1]:
import tensorflow as tf

x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]
#Training Data

# Evaluation our model using this test dataset
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]
#Test Data

#Training 데이터와 Test 데이터를 분리해야 한다.

X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])
#Placeholder를 이용하기 때문에 학습 데이터와 테스트 데이터를 feed_dict 따로 넣어주기만 하면 된다.

W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))
#tf.placeholder()는 입력 데이터를 만들 때 주로 사용한다. (실제 훈련 예제를 제공하는 변수) - 초기값을 지정할 필요 없다. (모델 입력시 변경되지 않을 데이터)
#tf.Variable()은 데이터의 상태를 저장할 때 주로 사용한다. (가중치나 편향 등의 학습 가능한 변수) - 초기값을 지정해야 한다. (학습 되는 데이터)
#http://stackoverflow.com/questions/36693740/whats-the-difference-between-tf-placeholder-and-tf-variable

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1)) #Cross entropy
# Try to change learning_rate to small numbers
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-10).minimize(cost) #최적화

# Correct prediction Test model
prediction = tf.arg_max(hypothesis, 1) #arg_max : 가장 큰 값의 인덱스
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer()) #초기화

    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)
        #Training 데이터만으로 학습을 한다.

    # predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))
    #Test 데이터만으로 예측과 정확도 측정

0 6.50789 [[-0.65080774 -1.04305828  0.60942501]
 [ 0.47546631  0.35755107 -1.5768255 ]
 [ 0.70622247 -0.33584177 -1.81297767]]
1 6.50789 [[-0.65080774 -1.04305828  0.60942501]
 [ 0.47546631  0.35755107 -1.5768255 ]
 [ 0.70622247 -0.33584177 -1.81297767]]
2 6.50789 [[-0.65080774 -1.04305828  0.60942501]
 [ 0.47546631  0.35755107 -1.5768255 ]
 [ 0.70622247 -0.33584177 -1.81297767]]
3 6.50789 [[-0.65080774 -1.04305828  0.60942501]
 [ 0.47546631  0.35755107 -1.5768255 ]
 [ 0.70622247 -0.33584177 -1.81297767]]
4 6.50789 [[-0.65080774 -1.04305828  0.60942501]
 [ 0.47546631  0.35755107 -1.5768255 ]
 [ 0.70622247 -0.33584177 -1.81297767]]
5 6.50789 [[-0.65080774 -1.04305828  0.60942501]
 [ 0.47546631  0.35755107 -1.5768255 ]
 [ 0.70622247 -0.33584177 -1.81297767]]
6 6.50789 [[-0.65080774 -1.04305828  0.60942501]
 [ 0.47546631  0.35755107 -1.5768255 ]
 [ 0.70622247 -0.33584177 -1.81297767]]
7 6.50789 [[-0.65080774 -1.04305828  0.60942501]
 [ 0.47546631  0.35755107 -1.5768255 ]
 [ 0.70622247 -0

173 6.50789 [[-0.65080774 -1.04305828  0.60942501]
 [ 0.47546631  0.35755107 -1.5768255 ]
 [ 0.70622247 -0.33584177 -1.81297767]]
174 6.50789 [[-0.65080774 -1.04305828  0.60942501]
 [ 0.47546631  0.35755107 -1.5768255 ]
 [ 0.70622247 -0.33584177 -1.81297767]]
175 6.50789 [[-0.65080774 -1.04305828  0.60942501]
 [ 0.47546631  0.35755107 -1.5768255 ]
 [ 0.70622247 -0.33584177 -1.81297767]]
176 6.50789 [[-0.65080774 -1.04305828  0.60942501]
 [ 0.47546631  0.35755107 -1.5768255 ]
 [ 0.70622247 -0.33584177 -1.81297767]]
177 6.50789 [[-0.65080774 -1.04305828  0.60942501]
 [ 0.47546631  0.35755107 -1.5768255 ]
 [ 0.70622247 -0.33584177 -1.81297767]]
178 6.50789 [[-0.65080774 -1.04305828  0.60942501]
 [ 0.47546631  0.35755107 -1.5768255 ]
 [ 0.70622247 -0.33584177 -1.81297767]]
179 6.50789 [[-0.65080774 -1.04305828  0.60942501]
 [ 0.47546631  0.35755107 -1.5768255 ]
 [ 0.70622247 -0.33584177 -1.81297767]]
180 6.50789 [[-0.65080774 -1.04305828  0.60942501]
 [ 0.47546631  0.35755107 -1.5768255 ]


# Learning rate
<img src="Images/lab7_1.png">

# Nomalize

<img src="Images/lab7_2.png">

<img src="Images/lab7_3.png">

In [2]:
import numpy as np

def MinMaxScaler(data):
    numerator = data - np.min(data, 0) #데이터 - 최소값. np.min(data, 0) : data의 최소값, 0차원에 대해. 열에 대한 최소값이 구해진다.
    denominator = np.max(data, 0) - np.min(data, 0) #최대값 - 최소값
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7) #0으로 나눠지는 것을 막기 위해 작은 값을 더한다.

xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])
#데이터가 크거나 들쑥날쑥한 경우에는 정규화를 해줘야 한다.

# very important. It does not work without it.
xy = MinMaxScaler(xy)
print(xy)
#정규화하지 않고 진행할 경우 값이 발산해서 Nan이 나온다.

x_data = xy[:, 0:-1] #전체 행을 가져온다, 각 행의 0 ~ index-1 행까지 가져온다.
y_data = xy[:, [-1]] #전체 행을 가져온다, 각 행의 마지막 행만 가져온다.

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4]) #전체 요소의 개수는 n, 각 요소는 4개씩
Y = tf.placeholder(tf.float32, shape=[None, 1]) #전체 요소의 개수는 n, 각 요소는 1개씩

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')
#tf.placeholder()는 입력 데이터를 만들 때 주로 사용한다. (실제 훈련 예제를 제공하는 변수) - 초기값을 지정할 필요 없다. (모델 입력시 변경되지 않을 데이터)
#tf.Variable()은 데이터의 상태를 저장할 때 주로 사용한다. (가중치나 편향 등의 학습 가능한 변수) - 초기값을 지정해야 한다. (학습 되는 데이터)
#http://stackoverflow.com/questions/36693740/whats-the-difference-between-tf-placeholder-and-tf-variable

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y)) #평균 제곱 오차

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost) #최적화

# Launch the graph in a session.
with tf.Session() as sess:
    # Initializes global variables in the graph.
    sess.run(tf.global_variables_initializer()) #초기화
    
    for step in range(101):
        cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)


[[ 0.99999999  0.99999999  0.          1.          1.        ]
 [ 0.70548491  0.70439552  1.          0.71881782  0.83755791]
 [ 0.54412549  0.50274824  0.57608696  0.606468    0.6606331 ]
 [ 0.33890353  0.31368023  0.10869565  0.45989134  0.43800918]
 [ 0.51436     0.42582389  0.30434783  0.58504805  0.42624401]
 [ 0.49556179  0.42582389  0.31521739  0.48131134  0.49276137]
 [ 0.11436064  0.          0.20652174  0.22007776  0.18597238]
 [ 0.          0.07747099  0.5326087   0.          0.        ]]
0 Cost:  0.555502 
Prediction:
 [[-0.1074009 ]
 [-0.24858361]
 [-0.21567595]
 [-0.19958508]
 [-0.17074841]
 [-0.10203714]
 [-0.167025  ]
 [-0.16953181]]
1 Cost:  0.555461 
Prediction:
 [[-0.10736327]
 [-0.24854736]
 [-0.21564589]
 [-0.19956191]
 [-0.17072086]
 [-0.10201059]
 [-0.16700752]
 [-0.16951475]]
2 Cost:  0.555421 
Prediction:
 [[-0.10732552]
 [-0.24851128]
 [-0.21561596]
 [-0.19953877]
 [-0.17069325]
 [-0.10198393]
 [-0.16699001]
 [-0.16949768]]
3 Cost:  0.55538 
Prediction:
 [[-0.