# Hypothesis not using matrix
<img src="Images/lab4_1.png">

In [1]:
import tensorflow as tf

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

#tf.placeholder()는 입력 데이터를 만들 때 주로 사용한다. (실제 훈련 예제를 제공하는 변수) - 초기값을 지정할 필요 없다. (모델 입력시 변경되지 않을 데이터)
#tf.Variable()은 데이터의 상태를 저장할 때 주로 사용한다. (가중치나 편향 등의 학습 가능한 변수) - 초기값을 지정해야 한다. (학습 되는 데이터)
#http://stackoverflow.com/questions/36693740/whats-the-difference-between-tf-placeholder-and-tf-variable

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5) #0.00001
train = optimizer.minimize(cost)

# Launch the graph in a session.
with tf.Session() as session:
    # Initializes global variables in the graph.
    session.run(tf.global_variables_initializer())
    
    for step in range(2001):
        cost_val, hy_val, _ = session.run([cost, hypothesis, train], feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
        
        if step % 10 == 0:
            print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
            
#결과값이 출력 되기는 하지만, 일일이 값을 입력하므로 비효율적이다.
#matrix를 쓰면 더 간단하게 정리할 수 있다.

0 Cost:  897.174 
Prediction:
 [ 124.50424194  152.93757629  148.89222717  162.29571533  117.54225159]
10 Cost:  0.273443 
Prediction:
 [ 150.99775696  184.77960205  180.26734924  196.46220398  141.82958984]
20 Cost:  0.265065 
Prediction:
 [ 151.0785675   184.87553406  180.36251831  196.56559753  141.90264893]
30 Cost:  0.2649 
Prediction:
 [ 151.07943726  184.87539673  180.36300659  196.56590271  141.9024353 ]
40 Cost:  0.264735 
Prediction:
 [ 151.08009338  184.87498474  180.36323547  196.56593323  141.90202332]
50 Cost:  0.264568 
Prediction:
 [ 151.08074951  184.87457275  180.36346436  196.56594849  141.90161133]
60 Cost:  0.264403 
Prediction:
 [ 151.08135986  184.87413025  180.36364746  196.56591797  141.90116882]
70 Cost:  0.264235 
Prediction:
 [ 151.08201599  184.87371826  180.36387634  196.56593323  141.90075684]
80 Cost:  0.264076 
Prediction:
 [ 151.0826416   184.87329102  180.36408997  196.56593323  141.90031433]
90 Cost:  0.263908 
Prediction:
 [ 151.08328247  184.872863

950 Cost:  0.252039 
Prediction:
 [ 151.13226318  184.84059143  180.38093567  196.56513977  141.86839294]
960 Cost:  0.251923 
Prediction:
 [ 151.13278198  184.84024048  180.38111877  196.56512451  141.86805725]
970 Cost:  0.251801 
Prediction:
 [ 151.13330078  184.83990479  180.38130188  196.56509399  141.86776733]
980 Cost:  0.251693 
Prediction:
 [ 151.13378906  184.83956909  180.38146973  196.56507874  141.86743164]
990 Cost:  0.251573 
Prediction:
 [ 151.13430786  184.8392334   180.38165283  196.56504822  141.86712646]
1000 Cost:  0.251456 
Prediction:
 [ 151.13482666  184.83891296  180.38182068  196.56504822  141.86680603]
1010 Cost:  0.251337 
Prediction:
 [ 151.13534546  184.83857727  180.38201904  196.5650177   141.86651611]
1020 Cost:  0.251223 
Prediction:
 [ 151.135849    184.83825684  180.38218689  196.56500244  141.86619568]
1030 Cost:  0.251111 
Prediction:
 [ 151.13633728  184.83792114  180.38235474  196.56497192  141.8658905 ]
1040 Cost:  0.250996 
Prediction:
 [ 151.1

1860 Cost:  0.242776 
Prediction:
 [ 151.17428589  184.81314087  180.39552307  196.56237793  141.84362793]
1870 Cost:  0.242696 
Prediction:
 [ 151.17468262  184.81285095  180.39567566  196.56233215  141.84338379]
1880 Cost:  0.242606 
Prediction:
 [ 151.17510986  184.81259155  180.39581299  196.56231689  141.84317017]
1890 Cost:  0.242515 
Prediction:
 [ 151.17552185  184.81233215  180.39596558  196.56225586  141.84292603]
1900 Cost:  0.242432 
Prediction:
 [ 151.17593384  184.8120575   180.39610291  196.5622406   141.8427124 ]
1910 Cost:  0.242344 
Prediction:
 [ 151.17633057  184.81178284  180.39624023  196.56217957  141.84248352]
1920 Cost:  0.242254 
Prediction:
 [ 151.17674255  184.81152344  180.39637756  196.56213379  141.84225464]
1930 Cost:  0.242168 
Prediction:
 [ 151.17715454  184.8112793   180.39653015  196.56210327  141.84202576]
1940 Cost:  0.242082 
Prediction:
 [ 151.17756653  184.81098938  180.39668274  196.5620575   141.84181213]
1950 Cost:  0.241996 
Prediction:
 [ 

# Hypothesis using matrix
<img src="Images/lab4_2.png">

In [2]:
x_data = [[73., 80., 75.], [93., 88., 93.],
         [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]] #행렬로 생성. 인풋 데이터
y_data = [[152.], [185.], [180.], [196.], [142.]] #행렬로 생성. 정답 레이블

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3]) #shape=[None, 3] (개수 제한 없음(None), 각 요소는 3개의 값을 가진다)
Y = tf.placeholder(tf.float32, shape=[None, 1]) #shape=[None, 1] (개수 제한 없음(None), 각 요소는 1개의 값을 가진다)

W = tf.Variable(tf.random_normal([3, 1]), name='weight') #tf.random_normal 출력 텐서의 형태 (3, 1)
b = tf.Variable(tf.random_normal([1]), name='bias') #tf.random_normal 출력 텐서의 형태 1개의 랜덤 변수

# Hypothesis
hypothesis = tf.matmul(X, W) + b #행렬의 내적 + b
#tf.add(tf.matmul(X, W), b)와 같다

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5) #0.00001
train = optimizer.minimize(cost) #최적화

# Launch the graph in a session.
with tf.Session() as session:
    # Initializes global variables in the graph.
    session.run(tf.global_variables_initializer())
    
    for step in range(2001):
        cost_val, hy_val, _ = session.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
        #실제 실행은 train, 학습의 진행 상황 알아보기 위한 변수 cost, hypothesis
        
        if step % 10 == 0:
            print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  8489.74 
Prediction:
 [[ 75.51340485]
 [ 82.63728333]
 [ 85.77278137]
 [ 91.25099182]
 [ 62.82131958]]
10 Cost:  13.9258 
Prediction:
 [[ 156.94050598]
 [ 180.53379822]
 [ 182.21772766]
 [ 196.27891541]
 [ 137.4969635 ]]
20 Cost:  13.7751 
Prediction:
 [[ 157.17253113]
 [ 180.83981323]
 [ 182.50511169]
 [ 196.59370422]
 [ 137.73561096]]
30 Cost:  13.7024 
Prediction:
 [[ 157.15895081]
 [ 180.85049438]
 [ 182.50157166]
 [ 196.5916748 ]
 [ 137.74902344]]
40 Cost:  13.63 
Prediction:
 [[ 157.14465332]
 [ 180.86030579]
 [ 182.49716187]
 [ 196.58865356]
 [ 137.76168823]]
50 Cost:  13.5581 
Prediction:
 [[ 157.13037109]
 [ 180.87005615]
 [ 182.49276733]
 [ 196.5856781 ]
 [ 137.77433777]]
60 Cost:  13.4865 
Prediction:
 [[ 157.1161499 ]
 [ 180.87980652]
 [ 182.48838806]
 [ 196.58270264]
 [ 137.78695679]]
70 Cost:  13.4153 
Prediction:
 [[ 157.10195923]
 [ 180.88951111]
 [ 182.48400879]
 [ 196.57972717]
 [ 137.79953003]]
80 Cost:  13.3445 
Prediction:
 [[ 157.08779907]
 [ 180.89916992

1060 Cost:  7.97451 
Prediction:
 [[ 155.87049866]
 [ 181.73182678]
 [ 182.10420227]
 [ 196.32389832]
 [ 138.88900757]]
1070 Cost:  7.93313 
Prediction:
 [[ 155.85964966]
 [ 181.73922729]
 [ 182.10087585]
 [ 196.32168579]
 [ 138.89855957]]
1080 Cost:  7.8919 
Prediction:
 [[ 155.84883118]
 [ 181.74661255]
 [ 182.09753418]
 [ 196.31944275]
 [ 138.90811157]]
1090 Cost:  7.85091 
Prediction:
 [[ 155.83805847]
 [ 181.7539978 ]
 [ 182.09420776]
 [ 196.31724548]
 [ 138.91763306]]
1100 Cost:  7.81019 
Prediction:
 [[ 155.82730103]
 [ 181.76132202]
 [ 182.09088135]
 [ 196.3150177 ]
 [ 138.92710876]]
1110 Cost:  7.7696 
Prediction:
 [[ 155.8165741 ]
 [ 181.76869202]
 [ 182.08757019]
 [ 196.31280518]
 [ 138.93656921]]
1120 Cost:  7.72928 
Prediction:
 [[ 155.80587769]
 [ 181.77600098]
 [ 182.08427429]
 [ 196.31060791]
 [ 138.9460144 ]]
1130 Cost:  7.68917 
Prediction:
 [[ 155.79521179]
 [ 181.78329468]
 [ 182.08097839]
 [ 196.3084259 ]
 [ 138.95542908]]
1140 Cost:  7.6493 
Prediction:
 [[ 155.78

1810 Cost:  5.41336 
Prediction:
 [[ 155.13317871]
 [ 182.2358551 ]
 [ 181.87646484]
 [ 196.17321777]
 [ 139.53862   ]]
1820 Cost:  5.38579 
Prediction:
 [[ 155.12432861]
 [ 182.24189758]
 [ 181.87373352]
 [ 196.1714325 ]
 [ 139.54640198]]
1830 Cost:  5.35835 
Prediction:
 [[ 155.11549377]
 [ 182.24794006]
 [ 181.8710022 ]
 [ 196.16963196]
 [ 139.55415344]]
1840 Cost:  5.33099 
Prediction:
 [[ 155.10667419]
 [ 182.25396729]
 [ 181.86827087]
 [ 196.16784668]
 [ 139.56192017]]
1850 Cost:  5.30383 
Prediction:
 [[ 155.09788513]
 [ 182.25996399]
 [ 181.86553955]
 [ 196.1660614 ]
 [ 139.56964111]]
1860 Cost:  5.27679 
Prediction:
 [[ 155.08911133]
 [ 182.26596069]
 [ 181.86282349]
 [ 196.16427612]
 [ 139.5773468 ]]
1870 Cost:  5.24993 
Prediction:
 [[ 155.08036804]
 [ 182.27192688]
 [ 181.86012268]
 [ 196.16252136]
 [ 139.58502197]]
1880 Cost:  5.2232 
Prediction:
 [[ 155.07165527]
 [ 182.27790833]
 [ 181.85745239]
 [ 196.1607666 ]
 [ 139.59268188]]
1890 Cost:  5.19661 
Prediction:
 [[ 155.