# Hypothesis not using matrix
<img src="Images/lab4_1.png">

In [1]:
import tensorflow as tf

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

#tf.placeholder()는 입력 데이터를 만들 때 주로 사용한다. (실제 훈련 예제를 제공하는 변수) - 초기값을 지정할 필요 없다. (모델 입력시 변경되지 않을 데이터)
#tf.Variable()은 데이터의 상태를 저장할 때 주로 사용한다. (가중치나 편향 등의 학습 가능한 변수) - 초기값을 지정해야 한다. (학습 되는 데이터)
#http://stackoverflow.com/questions/36693740/whats-the-difference-between-tf-placeholder-and-tf-variable

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5) #0.00001
train = optimizer.minimize(cost)

# Launch the graph in a session.
with tf.Session() as session:
    # Initializes global variables in the graph.
    session.run(tf.global_variables_initializer())
    
    for step in range(2001):
        cost_val, hy_val, _ = session.run([cost, hypothesis, train], feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
        
        if step % 10 == 0:
            print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
            
#결과값이 출력 되기는 하지만, 일일이 값을 입력하므로 비효율적이다.
#matrix를 쓰면 더 간단하게 정리할 수 있다.

0 Cost:  104265.0 
Prediction:
 [-131.39982605 -162.47946167 -157.87942505 -169.67738342 -127.04102325]
10 Cost:  16.2242 
Prediction:
 [ 154.20874023  180.82597351  180.3722229   198.6708374   134.8203125 ]
20 Cost:  15.2017 
Prediction:
 [ 155.05963135  181.87387085  181.39169312  199.78167725  135.62532043]
30 Cost:  15.1339 
Prediction:
 [ 155.04896545  181.88618469  181.39080811  199.78138733  135.64042664]
40 Cost:  15.0664 
Prediction:
 [ 155.03575134  181.89537048  181.38687134  199.77775574  135.65312195]
50 Cost:  14.9994 
Prediction:
 [ 155.02253723  181.90447998  181.38293457  199.77410889  135.66575623]
60 Cost:  14.9327 
Prediction:
 [ 155.00938416  181.91357422  181.3789978   199.77046204  135.67835999]
70 Cost:  14.8663 
Prediction:
 [ 154.99624634  181.92266846  181.37507629  199.7668457   135.69094849]
80 Cost:  14.8003 
Prediction:
 [ 154.98318481  181.93173218  181.3711853   199.76324463  135.70350647]
90 Cost:  14.7347 
Prediction:
 [ 154.97010803  181.94073486  18

850 Cost:  10.6398 
Prediction:
 [ 154.07727051  182.55882263  181.10133362  199.50788879  136.57723999]
860 Cost:  10.5962 
Prediction:
 [ 154.06672668  182.56611633  181.09819031  199.50483704  136.58744812]
870 Cost:  10.5527 
Prediction:
 [ 154.0562439   182.57339478  181.09507751  199.50183105  136.59767151]
880 Cost:  10.5095 
Prediction:
 [ 154.04577637  182.58067322  181.09197998  199.49880981  136.60786438]
890 Cost:  10.4666 
Prediction:
 [ 154.0353241   182.58790588  181.08888245  199.49578857  136.61799622]
900 Cost:  10.4238 
Prediction:
 [ 154.0249176   182.59512329  181.08578491  199.49278259  136.62814331]
910 Cost:  10.3813 
Prediction:
 [ 154.01452637  182.60232544  181.0827179   199.48977661  136.63822937]
920 Cost:  10.339 
Prediction:
 [ 154.00415039  182.60949707  181.07962036  199.48678589  136.64828491]
930 Cost:  10.2969 
Prediction:
 [ 153.99383545  182.61665344  181.07658386  199.48379517  136.65835571]
940 Cost:  10.2551 
Prediction:
 [ 153.98353577  182.623

 [ 153.23814392  183.14105225  180.85308838  199.25946045  137.39944458]
1760 Cost:  7.47389 
Prediction:
 [ 153.22996521  183.14674377  180.85066223  199.25694275  137.40753174]
1770 Cost:  7.44681 
Prediction:
 [ 153.22180176  183.15242004  180.8482666   199.25447083  137.4156189 ]
1780 Cost:  7.41986 
Prediction:
 [ 153.21365356  183.15805054  180.84585571  199.25195312  137.42366028]
1790 Cost:  7.393 
Prediction:
 [ 153.20553589  183.16371155  180.8434906   199.24946594  137.43171692]
1800 Cost:  7.36634 
Prediction:
 [ 153.19744873  183.16932678  180.84107971  199.24699402  137.43972778]
1810 Cost:  7.33978 
Prediction:
 [ 153.18937683  183.17494202  180.8387146   199.24452209  137.44773865]
1820 Cost:  7.3134 
Prediction:
 [ 153.18132019  183.18052673  180.83633423  199.24205017  137.45570374]
1830 Cost:  7.28713 
Prediction:
 [ 153.17330933  183.18611145  180.83398438  199.23959351  137.46366882]
1840 Cost:  7.26102 
Prediction:
 [ 153.16529846  183.19166565  180.83163452  199.

# Hypothesis using matrix
<img src="Images/lab4_2.png">

In [2]:
x_data = [[73., 80., 75.], [93., 88., 93.],
         [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]] #행렬로 생성. 인풋 데이터
y_data = [[152.], [185.], [180.], [196.], [142.]] #행렬로 생성. 정답 레이블

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3]) #shape=[None, 3] (개수 제한 없음(None), 각 요소는 3개의 값을 가진다)
Y = tf.placeholder(tf.float32, shape=[None, 1]) #shape=[None, 1] (개수 제한 없음(None), 각 요소는 1개의 값을 가진다)

W = tf.Variable(tf.random_normal([3, 1]), name='weight') #tf.random_normal 출력 텐서의 형태 (3, 1)
b = tf.Variable(tf.random_normal([1]), name='bias') #tf.random_normal 출력 텐서의 형태 1개의 랜덤 변수

# Hypothesis
hypothesis = tf.matmul(X, W) + b #행렬의 내적 + b
#tf.add(tf.matmul(X, W), b)와 같다

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5) #0.00001
train = optimizer.minimize(cost) #최적화

# Launch the graph in a session.
with tf.Session() as session:
    # Initializes global variables in the graph.
    session.run(tf.global_variables_initializer())
    
    for step in range(2001):
        cost_val, hy_val, _ = session.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
        #실제 실행은 train, 학습의 진행 상황 알아보기 위한 변수 cost, hypothesis
        
        if step % 10 == 0:
            print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  24204.1 
Prediction:
 [[ 13.5642662 ]
 [ 18.44753647]
 [ 16.88653946]
 [ 20.06489563]
 [ 13.32614517]]
10 Cost:  2.13128 
Prediction:
 [[ 151.18180847]
 [ 183.85848999]
 [ 179.86625671]
 [ 197.54545593]
 [ 139.49449158]]
20 Cost:  1.90629 
Prediction:
 [[ 151.59564209]
 [ 184.36077881]
 [ 180.3586731 ]
 [ 198.0814209 ]
 [ 139.87905884]]
30 Cost:  1.90286 
Prediction:
 [[ 151.59431458]
 [ 184.36408997]
 [ 180.35942078]
 [ 198.08197021]
 [ 139.88302612]]
40 Cost:  1.89948 
Prediction:
 [[ 151.59178162]
 [ 184.36590576]
 [ 180.35871887]
 [ 198.08094788]
 [ 139.885849  ]]
50 Cost:  1.89607 
Prediction:
 [[ 151.5892334 ]
 [ 184.36772156]
 [ 180.35801697]
 [ 198.07991028]
 [ 139.88868713]]
60 Cost:  1.89267 
Prediction:
 [[ 151.58668518]
 [ 184.36952209]
 [ 180.3572998 ]
 [ 198.07884216]
 [ 139.89149475]]
70 Cost:  1.88934 
Prediction:
 [[ 151.58415222]
 [ 184.37129211]
 [ 180.35658264]
 [ 198.07780457]
 [ 139.89427185]]
80 Cost:  1.88599 
Prediction:
 [[ 151.58161926]
 [ 184.373092

740 Cost:  1.69537 
Prediction:
 [[ 151.43028259]
 [ 184.48034668]
 [ 180.3139801 ]
 [ 198.0118103 ]
 [ 140.06706238]]
750 Cost:  1.69287 
Prediction:
 [[ 151.42823792]
 [ 184.48182678]
 [ 180.31343079]
 [ 198.01087952]
 [ 140.06944275]]
760 Cost:  1.69039 
Prediction:
 [[ 151.42616272]
 [ 184.48329163]
 [ 180.31285095]
 [ 198.00996399]
 [ 140.07182312]]
770 Cost:  1.68793 
Prediction:
 [[ 151.42408752]
 [ 184.48474121]
 [ 180.31225586]
 [ 198.00900269]
 [ 140.07415771]]
780 Cost:  1.68548 
Prediction:
 [[ 151.42202759]
 [ 184.4861908 ]
 [ 180.31170654]
 [ 198.0080719 ]
 [ 140.07650757]]
790 Cost:  1.68304 
Prediction:
 [[ 151.41998291]
 [ 184.48765564]
 [ 180.31114197]
 [ 198.00715637]
 [ 140.07885742]]
800 Cost:  1.68059 
Prediction:
 [[ 151.41793823]
 [ 184.48910522]
 [ 180.31057739]
 [ 198.00622559]
 [ 140.08120728]]
810 Cost:  1.67816 
Prediction:
 [[ 151.41592407]
 [ 184.49057007]
 [ 180.31002808]
 [ 198.00531006]
 [ 140.08355713]]
820 Cost:  1.67574 
Prediction:
 [[ 151.41389465

1500 Cost:  1.53301 
Prediction:
 [[ 151.28933716]
 [ 184.58093262]
 [ 180.27581787]
 [ 197.94500732]
 [ 140.23216248]]
1510 Cost:  1.53117 
Prediction:
 [[ 151.28770447]
 [ 184.5821228 ]
 [ 180.27539062]
 [ 197.94418335]
 [ 140.23416138]]
1520 Cost:  1.52937 
Prediction:
 [[ 151.28605652]
 [ 184.58328247]
 [ 180.27494812]
 [ 197.94334412]
 [ 140.2361145 ]]
1530 Cost:  1.52755 
Prediction:
 [[ 151.28442383]
 [ 184.5844574 ]
 [ 180.27452087]
 [ 197.94252014]
 [ 140.23809814]]
1540 Cost:  1.52576 
Prediction:
 [[ 151.28279114]
 [ 184.58564758]
 [ 180.27409363]
 [ 197.94171143]
 [ 140.24006653]]
1550 Cost:  1.52396 
Prediction:
 [[ 151.28117371]
 [ 184.58680725]
 [ 180.27366638]
 [ 197.94090271]
 [ 140.24205017]]
1560 Cost:  1.52217 
Prediction:
 [[ 151.27954102]
 [ 184.58795166]
 [ 180.27319336]
 [ 197.94004822]
 [ 140.24398804]]
1570 Cost:  1.5204 
Prediction:
 [[ 151.27792358]
 [ 184.58911133]
 [ 180.27278137]
 [ 197.9392395 ]
 [ 140.24594116]]
1580 Cost:  1.51862 
Prediction:
 [[ 151.

# Loading data from file

In [3]:
#Numpy Slicing
import numpy as np

nums = range(5)    # range is a built-in function that creates a list of integers
print(nums)         # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])    # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])     # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])     # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])      # Get a slice of the whole list; prints ["0, 1, 2, 3, 4]"
print(nums[:-1])    # Slice indices can be negative; prints ["0, 1, 2, 3]"
# nums[2:4] = [8, 9] # Assign a new sublist to a slice #Error
# print(nums) # Prints "[0, 1, 8, 9, 4]"




a = np.array([1, 2, 3, 4, 5]) # array([1, 2, 3, 4, 5])
print(a[1:3]) # array([2, 3])
print(a[-1]) # 5
a[0:2] = 9
print(a) # array([9, 9, 3, 4, 5])




b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
# array([[ 1,  2,  3,  4],
#        [ 5,  6,  7,  8],
#        [ 9, 10, 11, 12]])

print(b[:, 1]) # array([ 2, 6, 10]) #각 열의 1번째 인덱스(콤마 기준)
print(b[-1]) # array([ 9, 10, 11, 12])
print(b[-1, :]) # array([ 9, 10, 11, 12])
print(b[-1, ...]) # array([ 9, 10, 11, 12])
print(b[0:2, :]) #0<x<2 열의 모든 요소를 가져온다. (콤마 기준)
# array([[1, 2, 3, 4],
#        [5, 6, 7, 8]])


range(0, 5)
range(2, 4)
range(2, 5)
range(0, 2)
range(0, 5)
range(0, 4)
[2 3]
5
[9 9 3 4 5]
[ 2  6 10]
[ 9 10 11 12]
[ 9 10 11 12]
[ 9 10 11 12]
[[1 2 3 4]
 [5 6 7 8]]


In [4]:
# Lab 4 Multi-variable linear regression
import numpy as np

xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
#numpy로 파일 불러오기 (파일 위치 + 이름, 분할단위, 데이터 타입 = float32)
#같은 데이터 타입인 경우에만 사용 가능하다.
x_data = xy[:, 0:-1] #전체 열을 가져온다, 각 열의 0 ~ index-1 행까지 가져온다.
y_data = xy[:, [-1]] #전체 열을 가져온다, 각 열의 마지막 행만 가져온다.

# Make sure the shape and data are OK
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(25, 3) [[  73.   80.   75.]
 [  93.   88.   93.]
 [  89.   91.   90.]
 [  96.   98.  100.]
 [  73.   66.   70.]
 [  53.   46.   55.]
 [  69.   74.   77.]
 [  47.   56.   60.]
 [  87.   79.   90.]
 [  79.   70.   88.]
 [  69.   70.   73.]
 [  70.   65.   74.]
 [  93.   95.   91.]
 [  79.   80.   73.]
 [  70.   73.   78.]
 [  93.   89.   96.]
 [  78.   75.   68.]
 [  81.   90.   93.]
 [  88.   92.   86.]
 [  78.   83.   77.]
 [  82.   86.   90.]
 [  86.   82.   89.]
 [  78.   83.   85.]
 [  76.   83.   71.]
 [  96.   93.   95.]] 25
(25, 1) [[ 152.]
 [ 185.]
 [ 180.]
 [ 196.]
 [ 142.]
 [ 101.]
 [ 149.]
 [ 115.]
 [ 175.]
 [ 164.]
 [ 141.]
 [ 141.]
 [ 184.]
 [ 152.]
 [ 148.]
 [ 192.]
 [ 147.]
 [ 183.]
 [ 177.]
 [ 159.]
 [ 177.]
 [ 175.]
 [ 175.]
 [ 149.]
 [ 192.]]


In [5]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3]) #데이터와 shape를 일치시킨다.
Y = tf.placeholder(tf.float32, shape=[None, 1]) #정답레이블과 shape를 일치시킨다.
#placeholder는 입력값, 정답 레이블 등 바뀌지 않는 상수. session.run()시에 값 입력

W = tf.Variable(tf.random_normal([3, 1]), name='weight') #들어오는 값 3, 나가는 값 1. 3x1 행렬
b = tf.Variable(tf.random_normal([1]), name='bias') #나가는 값 1
#Variable은 가중치, 편향 등 바뀌는 변수

# Hypothesis
hypothesis = tf.matmul(X, W) + b #행렬 내적곱

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y)) #오차 제곱의 평균

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5) #학습률 0.00005. 손실함수 GeadientDescent
train = optimizer.minimize(cost) #코스트 최적화

# Launch the graph in a session.
with tf.Session() as session:
    session.run(tf.global_variables_initializer()) #초기화
    
    for step in range(2001):
        cost_val, hy_val, _ = session.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
        
        if step % 10 == 0: #10번 마다 출력
            print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
            
    # Ask my score
    #학습된 모델로 예측하기
    print("Your score will be ", session.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))
    print("Other scores will be ", session.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))
    #학습이 아닌 단순 예측이므로 hypothesis만으로 run 하면 된다.

0 Cost:  10503.9 
Prediction:
 [[ 59.63410568]
 [ 68.06125641]
 [ 68.88246918]
 [ 74.36335754]
 [ 51.76081085]
 [ 37.14612198]
 [ 56.02641678]
 [ 42.05126953]
 [ 62.18771362]
 [ 56.1149559 ]
 [ 53.57889938]
 [ 51.11961746]
 [ 71.65141296]
 [ 60.30874252]
 [ 55.70664597]
 [ 68.82714081]
 [ 57.11124802]
 [ 67.47374725]
 [ 68.97124481]
 [ 62.08327866]
 [ 65.24134064]
 [ 63.57723999]
 [ 62.69927597]
 [ 61.34506607]
 [ 71.30397034]]
10 Cost:  19.508 
Prediction:
 [[ 155.2315979 ]
 [ 182.98202515]
 [ 182.10409546]
 [ 197.67808533]
 [ 139.40551758]
 [ 101.77749634]
 [ 148.33737183]
 [ 110.49215698]
 [ 169.60383606]
 [ 155.6275177 ]
 [ 142.51411438]
 [ 138.8240509 ]
 [ 188.61740112]
 [ 157.53205872]
 [ 148.44596863]
 [ 185.45011902]
 [ 149.7008667 ]
 [ 178.25587463]
 [ 180.47706604]
 [ 161.85350037]
 [ 173.4908905 ]
 [ 171.39456177]
 [ 165.90266418]
 [ 157.71238708]
 [ 190.39903259]]
20 Cost:  18.897 
Prediction:
 [[ 155.8782959 ]
 [ 183.78045654]
 [ 182.8792572 ]
 [ 198.53015137]
 [ 140.01322

390 Cost:  15.4194 
Prediction:
 [[ 155.41246033]
 [ 183.93603516]
 [ 182.64189148]
 [ 198.53970337]
 [ 140.08842468]
 [ 102.79261017]
 [ 149.18580627]
 [ 111.38388824]
 [ 171.00331116]
 [ 157.59944153]
 [ 143.26776123]
 [ 139.99794006]
 [ 188.9034729 ]
 [ 157.42474365]
 [ 149.43885803]
 [ 186.6131134 ]
 [ 149.49220276]
 [ 179.27774048]
 [ 180.59246826]
 [ 161.92709351]
 [ 174.49345398]
 [ 172.51170349]
 [ 166.71742249]
 [ 157.26437378]
 [ 191.14215088]]
400 Cost:  15.3402 
Prediction:
 [[ 155.40084839]
 [ 183.93971252]
 [ 182.63587952]
 [ 198.5398407 ]
 [ 140.09010315]
 [ 102.80619049]
 [ 149.19087219]
 [ 111.39405823]
 [ 171.01898193]
 [ 157.63026428]
 [ 143.27104187]
 [ 140.01152039]
 [ 188.89076233]
 [ 157.4058075 ]
 [ 149.4473114 ]
 [ 186.62159729]
 [ 149.47154236]
 [ 179.28392029]
 [ 180.57655334]
 [ 161.91215515]
 [ 174.49954224]
 [ 172.52053833]
 [ 166.71983337]
 [ 157.23742676]
 [ 191.14004517]]
410 Cost:  15.2617 
Prediction:
 [[ 155.38926697]
 [ 183.94335938]
 [ 182.62989807

690 Cost:  13.3219 
Prediction:
 [[ 155.08636475]
 [ 184.03794861]
 [ 182.47242737]
 [ 198.54319763]
 [ 140.13363647]
 [ 103.17368317]
 [ 149.329422  ]
 [ 111.6729126 ]
 [ 171.44282532]
 [ 158.46632385]
 [ 143.36019897]
 [ 140.37905884]
 [ 188.54450989]
 [ 156.89051819]
 [ 149.67770386]
 [ 186.85015869]
 [ 148.90829468]
 [ 179.45451355]
 [ 180.14427185]
 [ 161.50672913]
 [ 174.66590881]
 [ 172.75924683]
 [ 166.78636169]
 [ 156.50563049]
 [ 191.08164978]]
700 Cost:  13.2611 
Prediction:
 [[ 155.07626343]
 [ 184.04107666]
 [ 182.46717834]
 [ 198.5433197 ]
 [ 140.13497925]
 [ 103.18548584]
 [ 149.33396912]
 [ 111.68200684]
 [ 171.45645142]
 [ 158.49324036]
 [ 143.36309814]
 [ 140.39089966]
 [ 188.53334045]
 [ 156.87388611]
 [ 149.68519592]
 [ 186.85752869]
 [ 148.89006042]
 [ 179.46011353]
 [ 180.13034058]
 [ 161.4936676 ]
 [ 174.67132568]
 [ 172.76693726]
 [ 166.78855896]
 [ 156.48205566]
 [ 191.07974243]]
710 Cost:  13.2007 
Prediction:
 [[ 155.06619263]
 [ 184.04417419]
 [ 182.46191406

1000 Cost:  11.663 
Prediction:
 [[ 154.79420471]
 [ 184.12738037]
 [ 182.31956482]
 [ 198.54718018]
 [ 140.17060852]
 [ 103.51526642]
 [ 149.46218872]
 [ 111.93973541]
 [ 171.83682251]
 [ 159.24734497]
 [ 143.4443512 ]
 [ 140.72177124]
 [ 188.2197876 ]
 [ 156.40635681]
 [ 149.89573669]
 [ 187.06268311]
 [ 148.37690735]
 [ 179.61947632]
 [ 179.73974609]
 [ 161.12797546]
 [ 174.82421875]
 [ 172.98132324]
 [ 166.85134888]
 [ 155.82110596]
 [ 191.02490234]]
1010 Cost:  11.6166 
Prediction:
 [[ 154.78546143]
 [ 184.1300354 ]
 [ 182.31498718]
 [ 198.5473175 ]
 [ 140.17166138]
 [ 103.52548981]
 [ 149.46621704]
 [ 111.94784546]
 [ 171.84860229]
 [ 159.27076721]
 [ 143.44689941]
 [ 140.73204041]
 [ 188.21003723]
 [ 156.39178467]
 [ 149.90231323]
 [ 187.06904602]
 [ 148.36088562]
 [ 179.62451172]
 [ 179.7276001 ]
 [ 161.11662292]
 [ 174.82902527]
 [ 172.98797607]
 [ 166.85334778]
 [ 155.80056763]
 [ 191.0231781 ]]
1020 Cost:  11.5707 
Prediction:
 [[ 154.77676392]
 [ 184.13265991]
 [ 182.310394

1340 Cost:  10.2934 
Prediction:
 [[ 154.51907349]
 [ 184.20959473]
 [ 182.17448425]
 [ 198.55184937]
 [ 140.20159912]
 [ 103.83715057]
 [ 149.59155273]
 [ 112.19949341]
 [ 172.20805359]
 [ 159.98751831]
 [ 143.52502441]
 [ 141.04580688]
 [ 187.91061401]
 [ 155.94441223]
 [ 150.10536194]
 [ 187.26296997]
 [ 147.86755371]
 [ 179.78189087]
 [ 179.35554504]
 [ 160.76901245]
 [ 174.97741699]
 [ 173.19076538]
 [ 166.91603088]
 [ 155.17137146]
 [ 190.96867371]]
1350 Cost:  10.2589 
Prediction:
 [[ 154.5116272 ]
 [ 184.21179199]
 [ 182.17054749]
 [ 198.55200195]
 [ 140.20239258]
 [ 103.84587097]
 [ 149.59513855]
 [ 112.20666504]
 [ 172.21810913]
 [ 160.00764465]
 [ 143.52723694]
 [ 141.05461121]
 [ 187.90220642]
 [ 155.93182373]
 [ 150.1111145 ]
 [ 187.2684021 ]
 [ 147.8536377 ]
 [ 179.78640747]
 [ 179.34509277]
 [ 160.75926208]
 [ 174.98164368]
 [ 173.19644165]
 [ 166.91784668]
 [ 155.15371704]
 [ 190.96713257]]
1360 Cost:  10.2248 
Prediction:
 [[ 154.50422668]
 [ 184.213974  ]
 [ 182.16662

1680 Cost:  9.2758 
Prediction:
 [[ 154.28471375]
 [ 184.27767944]
 [ 182.04983521]
 [ 198.55671692]
 [ 140.2243042 ]
 [ 104.11154938]
 [ 149.70605469]
 [ 112.429039  ]
 [ 172.52453613]
 [ 160.62266541]
 [ 143.59515381]
 [ 141.32315063]
 [ 187.64401245]
 [ 155.54510498]
 [ 150.28817749]
 [ 187.43377686]
 [ 147.42503357]
 [ 179.92718506]
 [ 179.02514648]
 [ 160.46099854]
 [ 175.11193848]
 [ 173.36947632]
 [ 166.97454834]
 [ 154.6129303 ]
 [ 190.91810608]]
1690 Cost:  9.25021 
Prediction:
 [[ 154.27838135]
 [ 184.27949524]
 [ 182.04644775]
 [ 198.55686951]
 [ 140.22488403]
 [ 104.11896515]
 [ 149.70921326]
 [ 112.43536377]
 [ 172.53311157]
 [ 160.6399231 ]
 [ 143.59709167]
 [ 141.33068848]
 [ 187.63674927]
 [ 155.53422546]
 [ 150.29318237]
 [ 187.43840027]
 [ 147.41293335]
 [ 179.93121338]
 [ 179.01617432]
 [ 160.45265198]
 [ 175.11564636]
 [ 173.37432861]
 [ 166.97618103]
 [ 154.5977478 ]
 [ 190.91668701]]
1700 Cost:  9.22485 
Prediction:
 [[ 154.27207947]
 [ 184.28129578]
 [ 182.043106

# Queue Runners

<img src="Images/lab4_4.png">
불러올 데이터가 매우 큰 경우 numpy에서 out of memory 오류가 날 수 있다.
tf의 Queue를 이용해서 불러올 수 있다.

<img src="Images/lab4_3.gif">

In [6]:
filename_queue = tf.train.string_input_producer(['data-01-test-score.csv'], shuffle=False, name='filename_queue')
#1. 불러올 파일들의 리스트를 정리한다.

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)
#2. TextLineReader를 정의해 파일을 로드한다.

# Default values, in case of empty columns. Also specifies the type of the
# decoded result.
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)
#3. Data를 가져온다.

# collect batches of csv in
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10) 
#[xy[0:-1], xy[-1:]] : x데이터, y데이터, 한번에 10개씩(batch_size) 가져온다.

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
with tf.Session() as session:
    # Initializes global variables in the graph.
    session.run(tf.global_variables_initializer())
    
    # Start populating the filename queue.
    coord = tf.train.Coordinator()
    threads = tf.train.start_queue_runners(sess=session, coord=coord) #큐를 시작
    
    for step in range(2001):
        x_batch, y_batch = session.run([train_x_batch, train_y_batch]) #배치또한 텐서 이므로 run이 필요하다. 
        cost_val, hy_val, _ = session.run([cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
        #가져온 배치를 feed_dict에 사용한다.
        
        if step % 10 == 0:
            print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
            
    
    coord.request_stop() #큐 종료
    coord.join(threads)
    
    # Ask my score
    print("Your score will be ", session.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))
    print("Other scores will be ", session.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

0 Cost:  7655.86 
Prediction:
 [[ 233.22401428]
 [ 285.93652344]
 [ 278.6960144 ]
 [ 306.05117798]
 [ 217.2428894 ]
 [ 164.44813538]
 [ 231.06114197]
 [ 173.94876099]
 [ 271.47912598]
 [ 257.36254883]]
10 Cost:  18.3909 
Prediction:
 [[ 151.26763916]
 [ 187.39570618]
 [ 181.62184143]
 [ 200.32124329]
 [ 142.08757019]
 [ 109.02133179]
 [ 151.91584778]
 [ 115.27249908]
 [ 179.3664856 ]
 [ 172.02110291]]
20 Cost:  15.1528 
Prediction:
 [[ 150.72621155]
 [ 186.72401428]
 [ 180.9712677 ]
 [ 199.60719299]
 [ 141.57466125]
 [ 108.63219452]
 [ 151.37898254]
 [ 114.87182617]
 [ 178.72712708]
 [ 171.41477966]]
30 Cost:  15.0468 
Prediction:
 [[ 150.73413086]
 [ 186.71281433]
 [ 180.97135925]
 [ 199.60180664]
 [ 141.56547546]
 [ 108.61451721]
 [ 151.37260437]
 [ 114.86441803]
 [ 178.7051239 ]
 [ 171.38040161]]
40 Cost:  14.9605 
Prediction:
 [[ 150.74569702]
 [ 186.70605469]
 [ 180.97579956]
 [ 199.60118103]
 [ 141.55970764]
 [ 108.59940338]
 [ 151.36979675]
 [ 114.85968781]
 [ 178.68734741]
 [ 1

420 Cost:  12.1727 
Prediction:
 [[ 151.15002441]
 [ 186.47149658]
 [ 181.13162231]
 [ 199.58111572]
 [ 141.3581543 ]
 [ 108.07350922]
 [ 151.27455139]
 [ 114.69828033]
 [ 178.06898499]
 [ 170.29318237]]
430 Cost:  12.1107 
Prediction:
 [[ 151.15975952]
 [ 186.46582031]
 [ 181.13537598]
 [ 199.58062744]
 [ 141.35325623]
 [ 108.06083679]
 [ 151.27229309]
 [ 114.69447327]
 [ 178.05407715]
 [ 170.26776123]]
440 Cost:  12.0493 
Prediction:
 [[ 151.16944885]
 [ 186.46017456]
 [ 181.13908386]
 [ 199.58015442]
 [ 141.34838867]
 [ 108.04824066]
 [ 151.27003479]
 [ 114.6906662 ]
 [ 178.03924561]
 [ 170.2424469 ]]
450 Cost:  11.9884 
Prediction:
 [[ 151.17912292]
 [ 186.45455933]
 [ 181.14280701]
 [ 199.57969666]
 [ 141.34355164]
 [ 108.03567505]
 [ 151.26780701]
 [ 114.68689728]
 [ 178.02449036]
 [ 170.2172699 ]]
460 Cost:  11.9281 
Prediction:
 [[ 151.18870544]
 [ 186.44895935]
 [ 181.14649963]
 [ 199.57923889]
 [ 141.33869934]
 [ 108.0231781 ]
 [ 151.26557922]
 [ 114.68312836]
 [ 178.00979614

840 Cost:  9.9723 
Prediction:
 [[ 151.5239563 ]
 [ 186.25332642]
 [ 181.27505493]
 [ 199.56323242]
 [ 141.16931152]
 [ 107.58733368]
 [ 151.18936157]
 [ 114.55457306]
 [ 177.49734497]
 [ 169.31900024]]
850 Cost:  9.92875 
Prediction:
 [[ 151.5320282 ]
 [ 186.24859619]
 [ 181.27813721]
 [ 199.56285095]
 [ 141.16519165]
 [ 107.57683563]
 [ 151.18756104]
 [ 114.55154419]
 [ 177.48500061]
 [ 169.29797363]]
860 Cost:  9.88565 
Prediction:
 [[ 151.54008484]
 [ 186.24391174]
 [ 181.28123474]
 [ 199.5625    ]
 [ 141.16111755]
 [ 107.56639099]
 [ 151.18577576]
 [ 114.54853821]
 [ 177.47273254]
 [ 169.27708435]]
870 Cost:  9.84283 
Prediction:
 [[ 151.54808044]
 [ 186.23921204]
 [ 181.28430176]
 [ 199.56211853]
 [ 141.1570282 ]
 [ 107.5559845 ]
 [ 151.18399048]
 [ 114.54553223]
 [ 177.460495  ]
 [ 169.25627136]]
880 Cost:  9.80034 
Prediction:
 [[ 151.55606079]
 [ 186.23454285]
 [ 181.28735352]
 [ 199.56173706]
 [ 141.15296936]
 [ 107.54560852]
 [ 151.18222046]
 [ 114.54253387]
 [ 177.44830322]

1250 Cost:  8.45323 
Prediction:
 [[ 151.82740784]
 [ 186.07522583]
 [ 181.39086914]
 [ 199.54937744]
 [ 141.0138855 ]
 [ 107.19303894]
 [ 151.1229248 ]
 [ 114.4430542 ]
 [ 177.03381348]
 [ 168.53147888]]
1260 Cost:  8.42225 
Prediction:
 [[ 151.83415222]
 [ 186.0712738 ]
 [ 181.39343262]
 [ 199.54908752]
 [ 141.01042175]
 [ 107.18428802]
 [ 151.12149048]
 [ 114.44063568]
 [ 177.02352905]
 [ 168.51405334]]
1270 Cost:  8.39145 
Prediction:
 [[ 151.84083557]
 [ 186.06730652]
 [ 181.39596558]
 [ 199.54878235]
 [ 141.00694275]
 [ 107.17558289]
 [ 151.12004089]
 [ 114.43823242]
 [ 177.01327515]
 [ 168.49667358]]
1280 Cost:  8.36099 
Prediction:
 [[ 151.84753418]
 [ 186.06340027]
 [ 181.39852905]
 [ 199.54849243]
 [ 141.00350952]
 [ 107.16690826]
 [ 151.11862183]
 [ 114.43585205]
 [ 177.00309753]
 [ 168.47941589]]
1290 Cost:  8.33071 
Prediction:
 [[ 151.85415649]
 [ 186.0594635 ]
 [ 181.40103149]
 [ 199.54818726]
 [ 141.00007629]
 [ 107.15827942]
 [ 151.1171875 ]
 [ 114.43347168]
 [ 176.992

1690 Cost:  7.30287 
Prediction:
 [[ 152.09709167]
 [ 185.91586304]
 [ 181.49317932]
 [ 199.53765869]
 [ 140.87361145]
 [ 106.84279633]
 [ 151.06646729]
 [ 114.34890747]
 [ 176.62210083]
 [ 167.83450317]]
1700 Cost:  7.28119 
Prediction:
 [[ 152.10261536]
 [ 185.91256714]
 [ 181.49525452]
 [ 199.53741455]
 [ 140.87068176]
 [ 106.83560944]
 [ 151.06533813]
 [ 114.34703827]
 [ 176.6136322 ]
 [ 167.82020569]]
1710 Cost:  7.25975 
Prediction:
 [[ 152.10813904]
 [ 185.90931702]
 [ 181.49736023]
 [ 199.53721619]
 [ 140.86781311]
 [ 106.82844543]
 [ 151.06422424]
 [ 114.3451767 ]
 [ 176.60523987]
 [ 167.80601501]]
1720 Cost:  7.23846 
Prediction:
 [[ 152.11364746]
 [ 185.90606689]
 [ 181.49945068]
 [ 199.5369873 ]
 [ 140.8649292 ]
 [ 106.82132721]
 [ 151.06311035]
 [ 114.34332275]
 [ 176.59686279]
 [ 167.79187012]]
1730 Cost:  7.21726 
Prediction:
 [[ 152.11909485]
 [ 185.90280151]
 [ 181.50149536]
 [ 199.53672791]
 [ 140.86204529]
 [ 106.81422424]
 [ 151.0619812 ]
 [ 114.34147644]
 [ 176.588

# Shuffle batch

In [ ]:
# min_after_dequeue defines how big a buffer we will randomly sample
#   from -- bigger means better shuffling but slower start up and more
#   memory used.
# capacity must be larger than min_after_dequeue and the amount larger
#   determines the maximum we will prefetch.  Recommendation:
#   min_after_dequeue + (num_threads + a small safety margin) * batch_size
min_after_dequeue = 10000
capacity = min_after_dequeue + 3 * batch_size
example_batch, label_batch = tf.train.shuffle_batch(
   [example, label], batch_size=batch_size, capacity=capacity,
   min_after_dequeue=min_after_dequeue)